package foodorderingsystem;

import domain.Customer;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.*;
import java.io.*;
import java.nio.file.*;
import java.util.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author HP
 */
public class AdminCustomerRegistration extends javax.swing.JFrame {

    /**
     * Creates new form CustomerRegistration
     */
    public AdminCustomerRegistration() {
        initComponents();
        getContentPane().setBackground(new Color(200, 249, 190)); // Set background color
        Login login = new Login();
        System.out.println(login.getUsername());
        ImageIcon img = new ImageIcon(getClass().getResource("/files/back.png"));
        Image scaledImage = img.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);//with 200px,height 200px
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        back.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                AdminChoose a = new AdminChoose();
                a.setVisible(true);
                dispose();
            }
        });

        back.setText("");
        back.setIcon(scaledIcon);
        setLocationRelativeTo(null);
        createCustomerPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        identityCard = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ic = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        phoneNum = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        postCode = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        custId = new javax.swing.JTextField();
        state = new javax.swing.JComboBox<>();
        city = new javax.swing.JComboBox<>();
        gender = new javax.swing.JComboBox<>();
        generateIdBtn = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        btnPanel = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(191, 255, 178));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Registration");

        back.setText("jLabel13");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(222, 222, 222))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back)
                    .addComponent(jLabel1))
                .addGap(23, 23, 23))
        );

        infoPanel.setBackground(new java.awt.Color(204, 255, 193));
        infoPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                infoPanelComponentShown(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel2.setText("Search Customer IC: ");

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel3.setText("Full Name :");

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel4.setText("Identity Card Number (IC) :");

        jLabel5.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel5.setText("Email Address :");

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel6.setText("Phone Number :");

        jLabel7.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel7.setText("Password :");

        jLabel8.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel8.setText("Address :");

        jLabel9.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel9.setText("City :");

        jLabel10.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel10.setText("Post Code :");

        jLabel11.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel11.setText("State/Province :");

        jLabel12.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel12.setText("Date od Bith(YYYY-MM-DD):");

        jLabel14.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        jLabel14.setText("Gender :");

        custId.setEditable(false);
        custId.setText("Customer ID");

        state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select State", "Johor ", "Kedah", "Kelantan", "Melaka", "Negeri Sembilan", "Pahang", "Perak", "Perlis", "Pulau Pinang ", "Sabah", "Sarawak", "Selangor", "Terengganu", "Kuala Lumpur", "Putrajaya ", "Labuan" }));

        city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selete", "Male", "Female" }));

        generateIdBtn.setBackground(new java.awt.Color(77, 214, 77));
        generateIdBtn.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        generateIdBtn.setText("Click Here To Generate Customer ID");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(identityCard, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, infoPanelLayout.createSequentialGroup()
                                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(generateIdBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(infoPanelLayout.createSequentialGroup()
                                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(infoPanelLayout.createSequentialGroup()
                                                .addGap(405, 405, 405)
                                                .addComponent(jLabel11))
                                            .addGroup(infoPanelLayout.createSequentialGroup()
                                                .addGap(103, 103, 103)
                                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, infoPanelLayout.createSequentialGroup()
                                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(48, 48, 48)
                                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10))
                                    .addGroup(infoPanelLayout.createSequentialGroup()
                                        .addComponent(ic, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9))
                                    .addGroup(infoPanelLayout.createSequentialGroup()
                                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(phoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(46, 46, 46)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(postCode, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custId, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(identityCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(ic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(phoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateIdBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPanel.setBackground(new java.awt.Color(204, 255, 193));

        deleteBtn.setBackground(new java.awt.Color(77, 214, 77));
        deleteBtn.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        deleteBtn.setText("DELETE");

        updateBtn.setBackground(new java.awt.Color(77, 214, 77));
        updateBtn.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        updateBtn.setText("UPDATE");

        createBtn.setBackground(new java.awt.Color(77, 214, 77));
        createBtn.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        createBtn.setText("CREATE");

        jButton1.setBackground(new java.awt.Color(77, 214, 77));
        jButton1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnPanelLayout = new javax.swing.GroupLayout(btnPanel);
        btnPanel.setLayout(btnPanelLayout);
        btnPanelLayout.setHorizontalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        btnPanelLayout.setVerticalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn)
                    .addComponent(updateBtn)
                    .addComponent(createBtn)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_infoPanelComponentShown

    }//GEN-LAST:event_infoPanelComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        identityCard.setText("");
        name.setText("");
        ic.setText("");
        email.setText("");
        phoneNum.setText("");
        address.setText("");
        state.setSelectedItem("Select");
        city.setSelectedItem("Select");
        postCode.setText("");
        dob.setText("");
        gender.setSelectedItem("Select");
        custId.setText("");
        password.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    Customer customer = new Customer();

    private void createCustomerPanel() {

        String[] defaultCities = {"Select City"};

        state.addActionListener(e -> {
            String selectedState = state.getSelectedItem().toString();
            switch (selectedState) {
                case "Johor":
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City", "Johor Bahru", "Mersing", "Batu Pahat", "Kluang", "Segamat", "Pontian"}));
                    break;
                case "Kedah":
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City", "Alor Setar", "Sungai Petani", "Kulim", "Langkawi", "Pendang"}));
                    break;
                case "Kelantan":
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City", "Kota Bharu", "Tanah Merah", "Machang", "Kuala Krai", "Gua Musang"}));
                    break;
                case "Melaka":
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City", "Melaka City", "Ayer Keroh", "Alor Gajah", "Jasin"}));
                    break;
                case "Negeri Sembilan":
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City", "Seremban", "Port Dickson", "Nilai", "Tampin"}));
                    break;
                case "Pahang":
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City", "Kuantan", "Temerloh", "Pekan", "Bentong", "Raub"}));
                    break;
                case "Perak":
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City", "Ipoh", "Taiping", "Teluk Intan", "Batu Gajah", "Parit Buntar"}));
                    break;
                case "Perlis":
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City", "Kangar", "Arau", "Padang Besar"}));
                    break;
                case "Pulau Pinang":
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City", "George Town", "Butterworth", "Bayan Lepas", "Seberang Jaya"}));
                    break;
                case "Sabah":
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City", "Kota Kinabalu", "Sandakan", "Tawau", "Keningau", "Lahad Datu"}));
                    break;
                case "Sarawak":
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City", "Kuching", "Miri", "Sibu", "Bintulu", "Limbang"}));
                    break;
                case "Selangor":
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City", "Shah Alam", "Petaling Jaya", "Subang Jaya", "Klang", "Kajang"}));
                    break;
                case "Terengganu":
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City", "Kuala Terengganu", "Dungun", "Kemaman", "Marang"}));
                    break;
                case "Kuala Lumpur":
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City", "Kuala Lumpur"}));
                    break;
                case "Putrajaya":
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City", "Putrajaya"}));
                    break;
                case "Labuan":
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City", "Labuan"}));
                    break;
                default:
                    city.setModel(new DefaultComboBoxModel<>(new String[]{"Select City"}));
                    break;
            }
        });

        generateIdBtn.addActionListener(e -> {
            String newCustId = customer.generateId();
            if (newCustId != null) {
                custId.setText(newCustId);
            } else {
                JOptionPane.showMessageDialog(this, "Error generating Customer ID", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        // Action when the user presses Enter in the Identity Card field
        identityCard.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    String enteredIc = identityCard.getText().trim();
                    boolean recordFound = false;

                    try (BufferedReader br = new BufferedReader(new FileReader("custRegistration.txt"))) {
                        String line;
                        while ((line = br.readLine()) != null) {
                            String[] columns = line.split("\\|");
                            if (columns.length >= 12 && columns[1].trim().equals(enteredIc)) {

                                customer.setName(columns[0]);
                                customer.setIc(columns[1]);
                                customer.setEmail(columns[2]);
                                customer.setPhoneNum(columns[3]);
                                customer.setAddres(columns[4]);
                                customer.setState(columns[5]);
                                customer.setCity(columns[6]);
                                customer.setPostalCode(columns[7]);
                                customer.setDob(columns[8]);
                                customer.setGender(columns[9]);
                                customer.setPassword(columns[10]);
                                customer.setId(columns[11]);

                                name.setText(customer.getName());
                                ic.setText(customer.getIc());
                                email.setText(customer.getEmail());
                                phoneNum.setText(customer.getPhoneNum());
                                address.setText(customer.getAddress());
                                state.setSelectedItem(customer.getState());
                                city.setSelectedItem(customer.getCity());
                                postCode.setText(customer.getPostalCode());
                                dob.setText(customer.getDob());
                                gender.setSelectedItem(customer.getGender());
                                address.setText(customer.getPassword());
                                custId.setText(customer.getId());

                                recordFound = true;
                                break;
                            }
                        }
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "An error occurred while reading the file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }

                    if (!recordFound) {
                        JOptionPane.showMessageDialog(null, "No Record Found", "Search Result", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            }
        });

        createBtn.addActionListener(e -> {

            customer.setName(name.getText());
            customer.setIc(ic.getText());
            customer.setEmail(email.getText());
            customer.setPhoneNum(phoneNum.getText());
            customer.setAddres(address.getText());
            customer.setState(state.getSelectedItem().toString());
            customer.setCity(city.getSelectedItem().toString());
            customer.setPostalCode(postCode.getText());
            customer.setDob(dob.getText());
            customer.setGender(gender.getSelectedItem().toString());
            customer.setId(custId.getText());
            customer.setPassword(new String(password.getPassword()));

            // Validate input
            if (customer.getName().isEmpty() || customer.getIc().isEmpty() || customer.getEmail().isEmpty() || customer.getPhoneNum().isEmpty()
                    || customer.getAddress().isEmpty() || customer.getState().equals("Select") || customer.getCity().equals("Select")
                    || customer.getPostalCode().isEmpty() || customer.getGender().equals("Select") || customer.getDob().isEmpty() || customer.getId().isEmpty()
                    || customer.getPassword().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all required fields!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                String validationMessage = customer.inputChecking(name.getText(), ic.getText(), email.getText(), phoneNum.getText(), address.getText(), dob.getText(), Arrays.toString(password.getPassword()), gender.getSelectedItem().toString(), state.getSelectedItem().toString(), city.getSelectedItem().toString(), postCode.getText());

                if (validationMessage != null) {
                    JOptionPane.showMessageDialog(this, validationMessage, "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                boolean recordFound = customer.searchRecord(customer.getIc());

                if (recordFound == false) {
                    try (BufferedWriter bw = new BufferedWriter(new FileWriter("custRegistration.txt", true))) {
                        String data = customer.getName() + "|" + customer.getIc() + "|" + customer.getEmail() + "|" + customer.getPhoneNum() + "|"
                                + customer.getAddress() + "|" + customer.getState() + "|" + customer.getCity() + "|" + customer.getPostalCode() + "|"
                                + customer.getDob() + "|" + customer.getGender() + "|" + customer.getPassword() + "|" + customer.getId();
                        bw.write(data);
                        bw.newLine();
                        addCustomerToBalance(custId.getText());
                        identityCard.setText("");
                        name.setText("");
                        ic.setText("");
                        email.setText("");
                        phoneNum.setText("");
                        address.setText("");
                        state.setSelectedItem("Select");
                        city.setSelectedItem("Select");
                        postCode.setText("");
                        dob.setText("");
                        gender.setSelectedItem("Select");
                        custId.setText("");
                        password.setText("");

                        JOptionPane.showMessageDialog(this, "Registration Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);

                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "An error occurred while saving data.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }

        });

        deleteBtn.addActionListener(e -> {
            try {
                String enteredIc = identityCard.getText().trim(); // Get IC from the search field

                if (enteredIc.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please enter an IC to delete.",
                            "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Load all lines from the file
                List<String> custLines = Files.readAllLines(Paths.get("custRegistration.txt"));
                List<String> updatedLines = new ArrayList<>();
                boolean found = false;

                // Iterate through all lines to find the matching IC
                for (String line : custLines) {
                    String[] custParts = line.split("\\|");

                    // Assuming the IC is the second field (index 1)
                    if (custParts.length > 1 && custParts[1].trim().equals(enteredIc)) {
                        found = true; // Mark record as found
                    } else {
                        updatedLines.add(line); // Add non-matching lines to the updated list
                    }
                }

                if (found) {
                    int option = JOptionPane.showConfirmDialog(null,
                            "Are you sure you want to delete this record?",
                            "Confirmation", JOptionPane.YES_NO_OPTION);

                    if (option == JOptionPane.YES_OPTION) {

                        Files.write(Paths.get("custRegistration.txt"), updatedLines);
                        JOptionPane.showMessageDialog(null, "Customer record deleted successfully.",
                                "Success", JOptionPane.INFORMATION_MESSAGE);

                        identityCard.setText("");
                        name.setText("");
                        ic.setText("");
                        email.setText("");
                        phoneNum.setText("");
                        address.setText("");
                        state.setSelectedItem("Select");
                        city.setSelectedItem("Select");
                        postCode.setText("");
                        dob.setText("");
                        address.setText("");
                        gender.setSelectedItem("Select");

                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No record found with the given IC.",
                            "Not Found", JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "An error occurred while processing the file: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        updateBtn.addActionListener(e -> {
            try {
                String enteredIc = identityCard.getText().trim();

                if (enteredIc.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please enter an IC to modify.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                customer.setName(name.getText());
                customer.setIc(ic.getText());
                customer.setEmail(email.getText());
                customer.setPhoneNum(phoneNum.getText());
                customer.setAddres(address.getText());
                customer.setState(state.getSelectedItem().toString());
                customer.setCity(city.getSelectedItem().toString());
                customer.setPostalCode(postCode.getText());
                customer.setDob(dob.getText());
                customer.setGender(gender.getSelectedItem().toString());

                customer.setPassword(new String(password.getPassword()));

                // Validate input
                if (customer.getName().isEmpty() || customer.getIc().isEmpty() || customer.getEmail().isEmpty() || customer.getPhoneNum().isEmpty()
                        || customer.getAddress().isEmpty() || customer.getState().equals("Select") || customer.getCity().equals("Select")
                        || customer.getPostalCode().isEmpty() || customer.getGender().equals("Select") || customer.getDob().isEmpty() || customer.getId().isEmpty()
                        || customer.getPassword().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please fill all required fields!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                List<String> custLines = Files.readAllLines(Paths.get("custRegistration.txt"));
                List<String> updatedLines = new ArrayList<>();
                boolean found = false;

                // Iterate through all lines to find the matching IC
                for (String line : custLines) {
                    String[] custParts = line.split("\\|");

                    if (custParts.length > 1 && custParts[1].trim().equals(enteredIc)) {
                        found = true;

                        String updatedRecord = customer.getName() + "|" + customer.getIc() + "|" + customer.getEmail() + "|" + customer.getPhoneNum() + "|"
                                + customer.getAddress() + "|" + customer.getState() + "|" + customer.getCity() + "|" + customer.getPostalCode() + "|"
                                + customer.getDob() + "|" + customer.getGender() + "|" + customer.getPassword() + "|" + custParts[11].trim();
                        updatedLines.add(updatedRecord);
                    } else {
                        updatedLines.add(line);
                    }
                }

                if (found) {
                    if (ic.getText().equals(enteredIc)) {
                        Files.write(Paths.get("custRegistration.txt"), updatedLines);
                        JOptionPane.showMessageDialog(null, "Record updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

                        identityCard.setText("");
                        name.setText("");
                        ic.setText("");
                        email.setText("");
                        phoneNum.setText("");
                        address.setText("");
                        state.setSelectedItem("Select");
                        city.setSelectedItem("Select");
                        postCode.setText("");
                        dob.setText("");
                        gender.setSelectedItem("Select");
                        custId.setText("");
                        address.setText("");
                    } else {
                        JOptionPane.showMessageDialog(null, "IC cannot be modify.", "Upadate Record Fail", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No record found with the given IC.", "Not Found", JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "An error occurred while processing the file: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

    }

    public void addCustomerToBalance(String customerId) {
        boolean exists = false;
        StringBuilder fileData = new StringBuilder();

        try (BufferedReader br = new BufferedReader(new FileReader("Balance.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] columns = line.split("\\|");
                if (columns.length >= 2 && columns[0].trim().equals(customerId)) {
                    exists = true; // if customer id is exits
                }
                fileData.append(line).append("\n"); //keep originally data
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "An error occurred while reading the file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (!exists) {
            //if user does not exits 
            fileData.append(customerId).append("|0.00\n");
            try (BufferedWriter bw = new BufferedWriter(new FileWriter("Balance.txt"))) {
                bw.write(fileData.toString());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "An error occurred while writing to the file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Customer already exists in balance file.");
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JLabel back;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JComboBox<String> city;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField custId;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton generateIdBtn;
    private javax.swing.JTextField ic;
    private javax.swing.JTextField identityCard;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phoneNum;
    private javax.swing.JTextField postCode;
    private javax.swing.JComboBox<String> state;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
