/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package foodorderingsystem;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.*;
import java.io.*;
import java.nio.file.*;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ManageReview extends javax.swing.JFrame {

    /**
     * Creates new form CustomerReview
     */
    public ManageReview() {
        initComponents();
        getContentPane().setBackground(new Color(191, 255, 191)); // Set background color
        Login login = new Login();
        System.out.println(login.getUsername());
        ImageIcon img = new ImageIcon(getClass().getResource("/files/back.png"));
        Image scaledImage = img.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);//with 200px,height 200px
        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        back.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                ManagerChoose next = new ManagerChoose();
                next.setVisible(true);
                dispose();
            }
        });

        back.setText("");
        back.setIcon(scaledIcon);
        setLocationRelativeTo(null);
        setupDateChangeListener();
        DisplayInfoInTable("All");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        selection = new javax.swing.JComboBox<>();
        back = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        record = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        sellerReplyTxt = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        customerId = new javax.swing.JTextField();
        food = new javax.swing.JTextField();
        review = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        commentToSeller = new javax.swing.JTextArea();
        reply1 = new javax.swing.JButton();
        reply2 = new javax.swing.JButton();
        reply3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        commentToRunner = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        runnerReplyTxt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        orderId = new javax.swing.JTextField();
        voucherCode = new javax.swing.JButton();
        voucherCodeTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(168, 255, 153));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel7.setText("Manage Comment Page");

        jLabel6.setText("Select Date For Filter Record :");

        selection.setBackground(new java.awt.Color(133, 191, 133));
        selection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Not Yet Reply", "Replied" }));
        selection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionActionPerformed(evt);
            }
        });

        back.setText("jLabel11");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(260, 260, 260)
                        .addComponent(selection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(back)
                        .addGap(302, 302, 302)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(back))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(191, 255, 191));

        record.setBackground(new java.awt.Color(163, 204, 155));
        record.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer ID", "Food", "Review", "Comment", "Seller Reply", "Runner Comment", "Seller Reply", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recordMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(record);

        sellerReplyTxt.setColumns(20);
        sellerReplyTxt.setRows(5);
        jScrollPane2.setViewportView(sellerReplyTxt);

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel2.setText("Customer ID : ");

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel3.setText("Food : ");

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel4.setText("Review : ");

        jLabel5.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel5.setText("Comment to seller : ");

        customerId.setEditable(false);

        food.setEditable(false);

        review.setEditable(false);

        commentToSeller.setEditable(false);
        commentToSeller.setColumns(20);
        commentToSeller.setRows(5);
        jScrollPane3.setViewportView(commentToSeller);

        reply1.setBackground(new java.awt.Color(133, 191, 133));
        reply1.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        reply1.setText("We're so happy to see your positive feedback! We hope our food brightens your day every time! 💖");
        reply1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reply1ActionPerformed(evt);
            }
        });

        reply2.setBackground(new java.awt.Color(133, 191, 133));
        reply2.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        reply2.setText("We’re truly sorry to hear that the taste and service didn’t meet your expectations this time. Your feedback is very important to us, and we’re committed to making improvements to serve you better in the future.  \n\nAs a token of our apology, we’d like to offer you a voucher code for a 10% discount on your next purchase. We hope this will give us another chance to brighten your day with an improved experience.  \n\nThank you for giving us the opportunity to make it right!\n\nCode : ");
        reply2.setActionCommand("We’re truly sorry to hear that the taste didn’t meet your expectations this time. Your feedback is very important to us, and we’re committed to making improvements to serve you better in the future.  \n\nAs a token of our apology, we’d like to offer you a voucher code for a 10% discount on your next purchase. We hope this will give us another chance to brighten your day with an improved experience.  \n\nThank you for giving us the opportunity to make it right!\n\nCode : ");
        reply2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reply2ActionPerformed(evt);
            }
        });

        reply3.setBackground(new java.awt.Color(133, 191, 133));
        reply3.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        reply3.setText("Thanks for your feedback. We've informed the team and will improve next time!");
        reply3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reply3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel8.setText("Seller Reply :");

        save.setBackground(new java.awt.Color(133, 191, 133));
        save.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        save.setText("Save Button");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel1.setText("Comment to Runner :");

        commentToRunner.setEditable(false);
        commentToRunner.setColumns(20);
        commentToRunner.setRows(5);
        jScrollPane4.setViewportView(commentToRunner);

        jLabel9.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel9.setText("Runner Reply : ");

        runnerReplyTxt.setColumns(20);
        runnerReplyTxt.setRows(5);
        jScrollPane5.setViewportView(runnerReplyTxt);

        jButton1.setBackground(new java.awt.Color(133, 191, 133));
        jButton1.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        jButton1.setText("Thank you for your feedback! We'll improve and look forward to serving you again!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(133, 191, 133));
        jButton2.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        jButton2.setText("We’re glad you’re happy with our service! We look forward to your next visit.");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(133, 191, 133));
        jButton3.setFont(new java.awt.Font("Rockwell", 0, 13)); // NOI18N
        jButton3.setText("We’ve made improvements based on your suggestions. Thank you for your understanding and support!");
        jButton3.setActionCommand("We’re truly sorry to hear that the delivery service didn’t meet your expectations this time. Your feedback is very important to us, and we’re committed to making improvements to serve you better in the future.  \n\nAs a token of our apology, we’d like to offer you a voucher code for a 10% discount on your next purchase. We hope this will give us another chance to brighten your day with an improved experience.  \n\nThank you for giving us the opportunity to make it right!\n\nCode : ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel10.setText("Order ID : ");

        orderId.setEditable(false);

        voucherCode.setBackground(new java.awt.Color(133, 191, 133));
        voucherCode.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        voucherCode.setText("Generate Vouhcer Code :");
        voucherCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voucherCodeActionPerformed(evt);
            }
        });

        voucherCodeTxt.setEditable(false);
        voucherCodeTxt.setBackground(new java.awt.Color(255, 255, 255));
        voucherCodeTxt.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(food, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(39, 39, 39)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(orderId, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customerId, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel4)
                        .addGap(45, 45, 45)
                        .addComponent(review, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(310, 310, 310))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(reply3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(reply2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(reply1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(save)
                            .addGap(39, 39, 39)
                            .addComponent(voucherCode)
                            .addGap(33, 33, 33)
                            .addComponent(voucherCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10)
                            .addComponent(orderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(food, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(review, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(reply2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reply3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reply1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save)
                            .addComponent(voucherCode)
                            .addComponent(voucherCodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try {
            List<String> commentLines = Files.readAllLines(Paths.get("feedback.txt"));
            List<String> updatedLines = new ArrayList<>();
            boolean recordUpdated = false;

            for (String line : commentLines) {
                String[] commentParts = line.split("\\|");
                if (commentParts.length >= 9) {
                    if (commentParts[0].equals(orderId.getText())) {
                        recordUpdated = true;

                        String updatedRecord = orderId.getText() + "|"
                                + customerId.getText() + "|"
                                + food.getText() + "|"
                                + review.getText() + "|"
                                + commentToSeller.getText() + "|"
                                + sellerReplyTxt.getText() + "|"
                                + commentToRunner.getText() + "|"
                                + runnerReplyTxt.getText() + "|"
                                + commentParts[8];

                        updatedLines.add(updatedRecord);
                    } else {
                        updatedLines.add(line);
                    }
                } else {
                    updatedLines.add(line);
                }
            }

            Files.write(Paths.get("feedback.txt"), updatedLines);

            if (recordUpdated) {
                JOptionPane.showMessageDialog(this, "Record updated successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "No matching record found.", "Warning", JOptionPane.WARNING_MESSAGE);
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "An error occurred while processing the file: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void reply3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reply3ActionPerformed
        sellerReplyTxt.setText("Thanks for your feedback. We've informed the team and will improve next time!");
    }//GEN-LAST:event_reply3ActionPerformed

    private void reply2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reply2ActionPerformed
        sellerReplyTxt.setText("We’re truly sorry to hear that the taste didn’t meet your expectations this time. Your feedback is very important to us, and we’re committed to making improvements to serve you better in the future."
                + "As a token of our apology, we’d like to offer you a voucher code for a 10% discount on your next purchase. We hope this will give us another chance to brighten your day with an improved experience."
                + "Thank you for giving us the opportunity to make it right!"
                + "Code : ");
    }//GEN-LAST:event_reply2ActionPerformed

    private void reply1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reply1ActionPerformed
        sellerReplyTxt.setText("We're so happy to see your positive feedback! We hope our food brightens your day every time! 💖");
    }//GEN-LAST:event_reply1ActionPerformed

    private void recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordMouseClicked
        recordShow();
    }//GEN-LAST:event_recordMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        runnerReplyTxt.setText("Thank you for your feedback! We'll improve and look forward to serving you again!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        runnerReplyTxt.setText("We're glad you're happy with our service! We look forward to your next visit.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        runnerReplyTxt.setText("We’re truly sorry to hear that the delivery service didn’t meet your expectations this time. Your feedback is very important to us, and we’re committed to making improvements to serve you better in the future."
                + "As a token of our apology, we’d like to offer you a voucher code for a 10% discount on your next purchase. We hope this will give us another chance to brighten your day with an improved experience."
                + "Thank you for giving us the opportunity to make it right!"
                + "Code : ");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void selectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionActionPerformed
        String select = (String) selection.getSelectedItem();
        if (date.getDate() != null && select != null) {
            String selectedDate = new SimpleDateFormat("yyyy-MM-dd").format(date.getDate());
            displayRecordsForDate(selectedDate, select);
        } else if (date.getDate() == null) {
            DisplayInfoInTable(select);
        }

    }//GEN-LAST:event_selectionActionPerformed

    private void voucherCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voucherCodeActionPerformed
        Random rand = new Random();
        int num = rand.nextInt(100);
        String voucherCode = "VOUCHER" + num;
        voucherCodeTxt.setText(voucherCode);

        try (FileWriter fw = new FileWriter("voucher.txt", true); // Append mode
                 BufferedWriter bw = new BufferedWriter(fw)) {
            bw.write(customerId.getText() + "|" + voucherCode + "|10%"); // 10% discount
            bw.newLine();
            bw.flush();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error saving voucher: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_voucherCodeActionPerformed

    private void setupDateChangeListener() {
        date.addPropertyChangeListener("date", evt -> {
            if (date.getDate() != null) {
                String selectedDate = new SimpleDateFormat("yyyy-MM-dd").format(date.getDate());
                String select = (String) selection.getSelectedItem();
                displayRecordsForDate(selectedDate, select);
            }
        });
    }

    private void displayRecords(String selectedDate, String select) {
        DefaultTableModel recordTablex = (DefaultTableModel) record.getModel();
        recordTablex.setRowCount(0);
        boolean recordsFound = false;

        try (BufferedReader reader = new BufferedReader(new FileReader("feedback.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] columns = line.split("\\|");
                if (columns.length == 9 && (selectedDate == null || columns[8].equals(selectedDate))) {
                    boolean addRow = false;

                    switch (select) {
                        case "Not Yet Reply":
                            addRow = (columns[5].trim().isEmpty() || columns[7].trim().isEmpty());

                            break;
                        case "Replied":
                            addRow = !(columns[5].trim().isBlank() || columns[7].trim().isBlank());
                            break;

                        case "All":
                            addRow = true;
                            break;
                        default:
                            break;
                    }

                    if (addRow) {
                        recordTablex.addRow(columns);
                        recordsFound = true;
                    }
                }
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "An error occurred while reading the file: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (!recordsFound) {
            JOptionPane.showMessageDialog(this, "No records found" + (selectedDate != null ? " for the selected date." : "."));
        }
    }

    private void displayRecordsForDate(String selectedDate, String select) {
        displayRecords(selectedDate, select);
    }

    private void DisplayInfoInTable(String select) {
        displayRecords(null, select);
    }

    public void recordShow() {
        DefaultTableModel recordTablex = (DefaultTableModel) record.getModel();
        int selectedRow = record.getSelectedRow();

        if (selectedRow >= 0) {
            String orderIdValue = recordTablex.getValueAt(selectedRow, 0).toString();
            String customerIdValue = recordTablex.getValueAt(selectedRow, 1).toString();
            String foodValue = recordTablex.getValueAt(selectedRow, 2).toString();
            String reviewValue = recordTablex.getValueAt(selectedRow, 3).toString();
            String commentToSellerValue = recordTablex.getValueAt(selectedRow, 4).toString();
            String sellerReplyValue = recordTablex.getValueAt(selectedRow, 5).toString();
            String commentToRunnerValue = recordTablex.getValueAt(selectedRow, 6).toString();
            String runnerReplyValue = recordTablex.getValueAt(selectedRow, 7).toString();

            orderId.setText(orderIdValue);
            customerId.setText(customerIdValue);
            food.setText(foodValue);
            review.setText(reviewValue);
            commentToSeller.setText(commentToSellerValue);
            sellerReplyTxt.setText(sellerReplyValue);
            commentToRunner.setText(commentToRunnerValue);
            runnerReplyTxt.setText(runnerReplyValue);

        }
    }

    public void clear() {
        orderId.setText("");
        customerId.setText("");
        food.setText("");
        review.setText("");
        commentToSeller.setText("");
        sellerReplyTxt.setText("");
        commentToRunner.setText("");
        runnerReplyTxt.setText("");
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JTextArea commentToRunner;
    private javax.swing.JTextArea commentToSeller;
    private javax.swing.JTextField customerId;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField food;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField orderId;
    private javax.swing.JTable record;
    private javax.swing.JButton reply1;
    private javax.swing.JButton reply2;
    private javax.swing.JButton reply3;
    private javax.swing.JTextField review;
    private javax.swing.JTextArea runnerReplyTxt;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> selection;
    private javax.swing.JTextArea sellerReplyTxt;
    private javax.swing.JButton voucherCode;
    private javax.swing.JTextField voucherCodeTxt;
    // End of variables declaration//GEN-END:variables
}
